grupozeety/OpenKyOS

core/builder/FormularioHtml.class.php, core/builder/HtmlBase.class.php, core/builder/controleshtml/BotonHtml.class.php, core/builder/controleshtml/FormBootstrap.class.php, core/builder/controleshtml/InputBootstrap.class.php, core/builder/controleshtml/ModalBootstrap.class.php, core/builder/controleshtml/RadioButtonBootstrapHtml.class.php, core/builder/controleshtml/SelectBootstrap.class.php
Generación de controles en bootstrap.
=> Emmanuel master temp

blocks/llamarApi/funcion/procesarAjax.php
=> Modifiacion ruta cookie.

blocks/gui/menuPrincipal/Sql.class.php
Corrección Sentencia Sql estado menu_enlace.
=> Corrección Sentencia Sql estado menu_enlace.

blocks/gui/pie/css/Estilo.php
=> modificación css pie página

blocks/consumoMateriales/Sql.class.php, blocks/gui/menuPrincipal/formulario/form.php, blocks/gui/menuPrincipal/funcion/GetLink.php
Ajustes:
- Menu
- Consumo de Materiales
- Redireccionar
=> Ajuste Varios

blocks/gui/menuPrincipal/formulario/form.php
=> Corrección Ruta Redirección

blocks/gui/menuPrincipal/funcion/GetLink.php
=> Eliminar Namespace

blocks/gui/menuPrincipal/formulario/form.php
Ajuste Instanciar Metodo GetLink
=> Ajuste Instanciar Metodo GetLink

blocks/consumoMateriales/Sql.class.php
=> Correción Ajuste SQl

blocks/consumoMateriales/Sql.class.php, blocks/consumoMateriales/formulario/form.php, blocks/consumoMateriales/funcion/registrarConsumo.php, blocks/consumoMateriales/script/ajax.php, blocks/llamarApi/funcion/consultar.php
Se realiza ajuste al caso de  uso consumo de materiales.
=> Ajustes Caso de Uso Consumo de Materiales.

blocks/reportes/materialNoConsumido/entidad/generarDocumentoPdf.php
=> Desarrollo reporte material no consumido

blocks/llamarApi/funcion/consultar.php, blocks/reportes/materialNoConsumido/entidad/procesarParametros.php
* Cambio de Variable "orden_trabajo" a "id_orden_trabajo"
* Adición de filtro "Material%20Issue" en función obtenerIdentificadoresSalida de llamar Api
=> Cambios respecto orden de trabajo

blocks/registroBeneficiario/Sql.class.php
Ajuste a consulta de parametros cargado a branch pruebas.
=> Ajuste a consulta de parametros.

blocks/registroBeneficiario/formulario/tabs/conformacionHogar.php, blocks/registroBeneficiario/formulario/tabs/datosBasicos.php
=> Ajustes campos readonly.

blocks/gestionBeneficiarios/generacionContrato/control/Sql.class.php, blocks/gestionBeneficiarios/generacionContrato/entidad/cargarRequisitos.php, blocks/gestionBeneficiarios/generacionContrato/entidad/generarContratoPdf.php, blocks/gestionBeneficiarios/generacionContrato/frontera/requisitosBeneficiario.php
Control de Cambios Permitir el  Mergue con Rama de Pruebas
=> Integración Generar Contrato 

blocks/consumoMateriales/Sql.class.php, blocks/consumoMateriales/css/Estilo.php, blocks/consumoMateriales/css/modalLoad.css, blocks/consumoMateriales/formulario/form.php, blocks/consumoMateriales/funcion/registrarConsumo.php, blocks/consumoMateriales/locale/es_es/Mensaje.php, blocks/consumoMateriales/script/Script.php, blocks/consumoMateriales/script/ajax.php, blocks/consumoMateriales/script/modalLoad.js, blocks/consumoMateriales/script/ready.js, blocks/consumoMateriales/script/ready.php, blocks/llamarApi/funcion/consultar.php, blocks/llamarApi/funcion/procesarAjax.php
Control de cambios a caso de uso consumo de materiales.
=> Arquitectura nodo

blocks/llamarApi/funcion/OpenProject.php, blocks/llamarApi/funcion/consultar.php, blocks/llamarApi/funcion/procesarAjax.php
Creación función registro paquetes trabajo OpenProject
=> Creación función registro paquetes trabajo OpenProject

blocks/consumoMateriales/script/ajax.php
Ajuste de consumo de materiales de Material Issue a Material Transfer
=> Ajuste consumo materiales.

blocks/gestionBeneficiarios/generacionContrato/frontera/gestionarContrato.php
con elementos faltantes generar el contrato
=> mensaje generación contrato

blocks/etl/entidad/crearDocumentoHojaCalculo.php, blocks/reportes/instalacionesGenerales/entidad/crearDocumentoHojaCalculo.php, blocks/reportes/instalacionesGenerales/entidad/generarReporte.php, blocks/reportes/instalacionesGenerales/frontera/parametrosReporte.php
=> Reporte Semanal

blocks/facturacion/estadoCuenta/frontera/asociar.php, blocks/facturacion/estadoCuenta/frontera/entradaCriterios.php, blocks/facturacion/masivoCalFactura/control/Sql.class.php, blocks/facturacion/masivoCalFactura/entidad/calcularFactura.php, blocks/facturacion/masivoCalFactura/entidad/procesarFormulario.php
generar facturas hasta el dia de generacion tiendo en cuenta pagos parciales a conceptos, moras y borradores
=> generar facturas hasta el dia de generacion
